UH2011 featured products
Dragons-2024/Dragons-2024-2 pull request #14
Opened 2024-09-19 03:20 UTC by LCCastillo03

![image](https://github.com/user-attachments/assets/2d607cd1-4d67-42c0-9880-63467e67d2fc)
Se crearon los productos destacados.

2024-09-19 03:51 UTC, JulianAlmario approved these changes
Esta bien

2024-09-19 13:49 UTC, estebanramirez13 approved these changes

2024-09-19 16:43 UTC, octavio-delahoz-uninorte commented on src/components/DesProductos.tsx
> +const ProductoDestacado: React.FC<ProductoDestacadoProps> = ({ imagen, nombre, precioNormal, precioDescuento, descuento, slug }) => {
Hola, por favor los nombres de componentes en Inglés. Igual aplica para las props y nombres de archivo. Por favor, solo debería ir en Español la información de los productos si así lo escogieron. Por ejemplo este componente se puede llamar: "FeaturedProduct" o el que ustedes consideren.

2024-09-19 16:44 UTC, octavio-delahoz-uninorte commented on src/pages/Home.tsx
> +import ListaProductosDestacados from "../utils/ListaProductos";
Aplica igual para esto. Nombre de arrays, objects y fields en Inglés.

2024-09-19 16:45 UTC, octavio-delahoz-uninorte requested changes
Por favor revisar comentarios. Todo el código debe estar en Inglés. Aplica para todo el equipo.

2024-09-19 16:46 UTC, octavio-delahoz-uninorte commented on src/components/DesProductos.tsx
> +interface ProductoDestacadoProps {
Igual, en Inglés los types e interfaces.

2024-09-19 16:49 UTC, octavio-delahoz-uninorte commented on src/utils/ListaProductos.tsx
> +const ListaProductosDestacados: React.FC = () => {
Esto lo puedes llevar a la carpeta de componentes. Este archivo debería tener solo el array de productos. Debería ser .ts

2024-09-20 02:14 UTC, octavio-delahoz-uninorte approved these changes

2024-09-20 02:26 UTC, merged